[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22"

# API proxy rules must appear BEFORE the SPA fallback
[[redirects]]
  from = "/api/*"
  to   = "https://n8n.artbachmann.eu/webhook/voice-assistant/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api"
  to   = "https://n8n.artbachmann.eu/webhook/voice-assistant"
  status = 200
  force = true

# Single Page Application fallback
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
